name: Push Docker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
env:
  arch: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
  dockerFile: src/Dockerfile
jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - registry: docker.io
            username: jaidchen
            imageName: jaidchen/$repo
            passwordId: dockerHubToken
          - registry: ghcr.io
            imageName: $repo
            username: ${{ github.actor }}
            passwordId: GITHUB_TOKEN
    steps:
      - name: Set name
        id: nameSetter
        shell: bash
        run: repoName=${{ github.event.repository.name }} && repo=${repoName##docker-} && printf '::set-output name=imageName::%s' ${{ matrix.imageName }}
      - name: Set up qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ${{ matrix.registry }}
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ secrets[matrix.passwordId] }}
      - name: Build and push to ${{ matrix.registry }}
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ env.dockerFile }}
          platforms: ${{ env.arch }}
          tags: ${{ steps.nameSetter.outputs.imageName }}:latest
          cache-from: type=registry,ref=${{ steps.nameSetter.outputs.imageName }}:buildcache
          cache-to: type=registry,ref=${{ steps.nameSetter.outputs.imageName }}:buildcache,mode=max
