name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavorSuffix: -debian
            image: debian:stable-slim
            arch: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          - flavorSuffix: ''
            image: ubuntu:rolling
            arch: ''
          - flavorSuffix: -ubuntu-latest
            image: ubuntu:latest
            arch: ''
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      buildArgs: image=${{ matrix.image }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
      arch: ${{ matrix.arch }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
