name: pushDocker
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  job:
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}