name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  test:
    name: Test Docker
    permissions:
      contents: read
    uses: jaid/workflows/.github/workflows/testDocker.yml@main
    with:
      test: stdout.includes('run.bash not found')
  pushDocker:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu:rolling
          - flavorSuffix: lts
            image: ubuntu:latest
          - flavorSuffix: debian
            image: debian:stable-slim
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      dockerHubUser: jaidchen
      arch: linux/amd64,linux/arm64/v8
      buildArgs: |
        image=${{ matrix.image }}
        flavorSuffix=${{ matrix.flavorSuffix }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
