name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  matrix:
    uses: ./.github/workflows/makeMatrix.yml
  test:
    name: test${{ matrix.id && format(' ({0})', matrix.id) }}
    needs:
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.output) }}
    permissions:
      contents: read
    uses: jaid/workflows/.github/workflows/testDocker.yml@main
    with:
      test: stdout.includes('run.bash not found')
      buildArgs: image=${{ matrix.base }}
      arch: ${{ matrix.platform }}
  pushDocker:
    name: push${{ matrix.id && format(' ({0})', matrix.id) }}
    needs:
      - test
      - matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.output) }}
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      dockerHubUser: jaidchen
      arch: ${{ matrix.platform }}
      buildArgs: |
        image=${{ matrix.base }}
      flavorSuffix: ${{ matrix.id }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}