name: Push Docker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
env:
  arch: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
  buildContext: src
  dockerHubUser: jaidchen
  dockerHubRegistry: docker.io
  githubRegistry: ghcr.io
jobs:
  job:
    uses: jaid/workflow-templates/src/dockerPush.yml
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}